name: Test
on:
    push:
        branches: ["*"]
    pull_request:
        branches: ["*"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up ALSA configuration
              run: |
                  cp asoundrc ~/.asoundrc
                  cat ~/.asoundrc  # Debug: Check the configuration

            - name: Update apt
              run: |
                  sudo apt-get update
                  sudo apt-get install -y alsa-utils jackd2 libjack-jackd2-dev
                  sudo apt-get install libasound2-dev libudev-dev 
                  sudo apt-get install pulseaudio
                  pulseaudio --start
                  aplay -l  # List available devices
            - name: Setup Jack
              run: |
                  echo "Setting up Jack..."
                  sudo usermod -a -G audio ${USER}
                  sleep 5
                  echo "Starting Jack..."
                  sudo -E su ${USER} -c "jackd -r -ddummy -r48000 -p480" &
                  echo "Waiting for Jack..."
                  sleep 5
              shell: bash
            - name: Install cargo-llvm-cov
              uses: taiki-e/install-action@cargo-llvm-cov
            - name: Install nextest
              run: cargo install --locked cargo-nextest
            - name: Generate coverage report
              run: |
                  cargo llvm-cov nextest --all-features --workspace --exclude app 
                  cargo llvm-cov report --codecov --output-path target/nextest/default/codecov.json
            - name: Codecov
              uses: codecov/codecov-action@v2
              with:
                  file: ./codecov.json,./junit.xml
                  token: ${{ secrets.CODECOV_TOKEN }}
                  slug: fanegui/league-voice
                  directory: target/nextest/default
